config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: 'dashboard#index'

  resources :boards do
    resources :lists, except: :show
  end

  resources :lists do
    resources :items
  end

  namespace :api do
    resources :boards do
      resources :lists, only: :index, controller: 'lists'
      resources :list_positions, only: %I[index update], controller: 'list_positions'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :user

  validates :name, presence: true

  has_many :lists, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list

  validates :title, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board

  has_many :items, dependent: :destroy

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
end

app/controllers/api/list_positions_controller.rb
module Api
  class ListPositionsController < ApplicationController
    protect_from_forgery with: :null_session

    def update
      lists = board.lists.to_a
      delete_index = lists.index { |list| list.id == params[:id].to_i }
      list = lists.delete_at(delete_index)
      lists.insert(params[:position].to_i, list)
      lists.each_with_index do |list, index|
        list.position = index
      end

      List.import lists, on_duplicate_key_update: { conflict_target: [:id], columns: [:position] }

      render json: ListSerializer.new(lists).serializable_hash.to_json
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end
  end
end

app/controllers/api/lists_controller.rb
module Api
  class ListsController < ApplicationController
    protect_from_forgery with: :null_session

    def index
      @lists = board.lists.order(position: :asc)

      render json: ListSerializer.new(@lists).serializable_hash.to_json
    end

    private

    def board
      @board ||= Board.find(params[:board_id])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #include Pundit::Authorization
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  #before_action :authenticate_user!

  def new
    @board = Board.new
  end

  def edit
    board
  end

  def show
    board
  end

  def create
    @board = Board.new(board_params.merge(user: current_user))

    if @board.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    authorize board

    if board.update(board_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    authorize board
    board.destroy
    redirect_to root_path
  end

  private

  def board_params
    params.require(:board).permit(:name)
  end

  def board
    @board ||= Board.find(params[:id])
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  #before_action :authenticate_user!

  def index
    @boards = Board.order(:created_at)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    #redirect_to dashboard_path #if user_signed_in?
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #before_action :authenticate_user!

  def new
    @item = list.items.new
  end


  def create
    @item = list.items.new(item_params)

    if @item.save
      redirect_to board_path(list.board)
    else
      render :new
    end
  end

  private

  def list
    @list ||= List.find(params[:list_id])
  end

  def item_params
    params.require(:item).permit(:title, :description)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  #before_action :authenticate_user!

  def new
    @list = board.lists.new
  end

  def edit
    @list = board.lists.find(params[:id])
  end

  def create
    @list = board.lists.new(list_params)

    if @list.save
      redirect_to board_path(board)
    else
      render :new
    end
  end

  def update
    @list = board.lists.find(params[:id])

    if @list.update(list_params)
      redirect_to board_path(board)
    else
      render :edit
    end
  end

  def destroy
    @list = board.lists.find(params[:id])
    @list.destroy
    respond_to do |format|
      format.json do
        render json: {}, status: 200
      end
    end
  end

  private

  def board
    @board ||= Board.find(params[:board_id])
  end

  def list_params
    params.require(:list).permit(:title)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User deleted.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_form.html.erb
<div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
  <%= form_with model: board, local: true, data: { turbo: false }, class: "space-y-8 divide-gray-200" do |f| %>
    <div class="space-y-8 divide-y divide-gray-200" style="margin-top: 0">
      <div class="pt-8">
        <div>
          <% if board.new_record? %>
            <h3 class="text-lg font-medium leading-6 text-gray-900">New Board</h3>
            <p class="mt-1 text-sm text-gray-500">This form creates a new board.</p>
          <% else %>
            <h3 class="text-lg font-medium leading-6 text-gray-900">Edit Board</h3>
            <p class="mt-1 text-sm text-gray-500">This form edits a board.</p>
          <% end %>
        </div>
        <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
          <div class="sm:col-span-6">
            <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
            <div class="mt-1">
              <%= f.text_field :name, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="pt-5">
      <div class="flex justify-end">
        <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
        <%= f.submit class: "cursor-pointer ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
      </div>
    </div>
  <% end %>
</div>

app/views/boards/edit.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-3xl">
    <%= render "form", board: @board %>
  </div>
</div>

app/views/boards/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <!-- We've used 3xl here, but feel free to try other max-widths based on your needs -->
  <div class="mx-auto max-w-3xl">
    <%= form_with model: @board, local: true, class: "space-y-8 divide-gray-200" do |f| %>
      <div class="space-y-8 divide-y divide-gray-200">
        <div class="pt-8">
          <div>
            <h3 class="text-lg font-medium leading-6 text-gray-900">New Board</h3>
            <p class="mt-1 text-sm text-gray-500">This form creates a new board.</p>
          </div>
          <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
            <div class="sm:col-span-6">
              <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
              <div class="mt-1">
                <%= f.text_field :name, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="pt-5">
        <div class="flex justify-end">
          <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          <%= f.submit "Create Board", class: "ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/boards/show.html.erb
<div class="mx-auto max-w-full px-24 py-12">
  <div
    data-controller="board"
    class="mx-auto max-w-full"
    data-api-url="<%= api_board_lists_path(@board) %>"
    data-list-positions-api-url="<%= api_board_list_positions_path(@board) %>"
    data-board-lists-url="<%= board_lists_path(@board) %>"
    id="board"
    style="overflow-x: scroll"
    >
  </div>
</div>

app/views/dashboard/index.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12">
  <div class="mx-auto max-w-4xl">

    <ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
      <% @boards.each do |board| %>
        <li class="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow">
          <div class="flex w-full items-center justify-between space-x-6 p-6">
            <div class="flex-1 truncate">
              <div class="flex items-center space-x-3">
                <h3 class="truncate text-sm font-medium text-gray-900"><%= link_to board.name, board_path(board), class: "link" %></h3>
              </div>
            </div>
          </div>
          <div>
            <div class="-mt-px flex divide-x divide-gray-200">
              <div class="flex w-0 flex-1">
                <%= link_to edit_board_path(board), class: "relative -mr-px inline-flex w-0 flex-1 items-center justify-center rounded-bl-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span class="ml-3">Edit</span>
                <% end %>
              </div>
              <div class="-ml-px flex w-0 flex-1">
                <%= link_to board_path(board), data: { "turbo-method": :delete }, class: "relative inline-flex w-0 flex-1 items-center justify-center rounded-br-lg border border-transparent py-4 text-sm font-medium text-gray-700 hover:text-gray-500" do %>
                  <span class="ml-3 text-red-700">Delete</span>
                <% end %>
              </div>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/home/index.html.erb
<h1>Hello world from home controller</h1>

app/views/items/new.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-3xl">
    <div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
      <%= form_with model: [@list, @item], local: true, data: { turbo: false }, class: "space-y-8 divide-gray-200" do |f| %>
        <div class="space-y-8 divide-y divide-gray-200" style="margin-top: 0">
          <div class="pt-8">
            <div>
              <% if @item.new_record? %>
                <h3 class="text-lg font-medium leading-6 text-gray-900">New Item</h3>
                <p class="mt-1 text-sm text-gray-500">This form creates a new item.</p>
              <% else %>
                <h3 class="text-lg font-medium leading-6 text-gray-900">Edit Item : <%= item.title %> </h3>
                <p class="mt-1 text-sm text-gray-500">This form edits a item.</p>
              <% end %>
            </div>
            <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :title, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1">
                  <%= f.text_field :title, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
                </div>
              </div>
            </div>
            <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :description, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1">
                  <%= f.text_area :description, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="pt-5">
          <div class="flex justify-end">
            <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
            <%= f.submit class: "cursor-pointer ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="bg-white shadow">
  <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
    <div class="flex h-16 justify-between">
      <div class="flex">
        <div class="-ml-2 mr-2 flex items-center md:hidden">
          <!-- Mobile menu button -->
          <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" aria-controls="mobile-menu" aria-expanded="false">
            <span class="sr-only">Open main menu</span>
            <!--
              Icon when menu is closed.

              Heroicon name: outline/bars-3

              Menu open: "hidden", Menu closed: "block"
            -->
            <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
            </svg>
            <!--
              Icon when menu is open.

              Heroicon name: outline/x-mark

              Menu open: "block", Menu closed: "hidden"
            -->
            <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
              <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        <div class="flex flex-shrink-0 items-center">
          <%= link_to root_path do %>
            <%= image_tag "trello-logo-official.png", class: "block h-8 w-auto" %>
          <% end %>
        </div>
        <div class="hidden md:ml-6 md:flex md:space-x-8">
          <% if user_signed_in? %>
            <!-- Current: "border-indigo-500 text-gray-900", Default: "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700" -->
            <%= link_to "Dashboard", root_path, class: "inline-flex items-center border-b-2 #{ "border-indigo-500" if controller_name == "dashboard" } px-1 pt-1 text-sm font-medium text-gray-900" %>
            <%= link_to "Log out", destroy_user_session_path, data: { "turbo-method": :delete }, class: "inline-flex items-center border-b-2 border-transparent px-1 pt-1 text-sm font-medium text-gray-500 hover:border-gray-300 hover:text-gray-700" %>
          <% end %>
        </div>
      </div>
      <div class="flex items-center">
        <% if user_signed_in? %>
          <div class="flex-shrink-0">
            <% if controller_name == "boards" && action_name == "show" %>
              <%=  link_to new_board_list_path(@board), class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
                <!-- Heroicon name: mini/plus -->
                <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                </svg>
                <span>New List</span>
              <% end %>
            <% else %>
              <%=  link_to new_board_path, class: "relative inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" do %>
                <!-- Heroicon name: mini/plus -->
                <svg class="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                  <path d="M10.75 4.75a.75.75 0 00-1.5 0v4.5h-4.5a.75.75 0 000 1.5h4.5v4.5a.75.75 0 001.5 0v-4.5h4.5a.75.75 0 000-1.5h-4.5v-4.5z" />
                </svg>
                <span>New Board</span>
              <% end %>
            <% end %>
          </div>
        <% else %>
          <div class="ml-4 flex flex-shrink-0 items-center">
            <!-- %= link_to "Register", new_user_registration_path, class: "link" %>
            <%= link_to "Log In", new_user_session_path, class: "ml-3 link" %> -->
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TrelloClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path("trello-logo.png") %>

  </head>

  <body class="bg-gray-100">
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
  <div class="mx-auto max-w-3xl">
    <div class="bg-white mt-12 px-8 py-12 rounded-xl drop-shadow-lg">
      <%= form_with model: [board, list], local: true, data: { turbo: false }, class: "space-y-8 divide-gray-200" do |f| %>
        <div class="space-y-8 divide-y divide-gray-200" style="margin-top: 0">
          <div class="pt-8">
            <div>
              <% if @list.new_record? %>
                <h3 class="text-lg font-medium leading-6 text-gray-900">New List</h3>
                <p class="mt-1 text-sm text-gray-500">This form creates a new list.</p>
              <% else %>
                <h3 class="text-lg font-medium leading-6 text-gray-900">Edit List : <%= list.title %> </h3>
                <p class="mt-1 text-sm text-gray-500">This form edits a list.</p>
              <% end %>
            </div>
            <div class="mt-6 grid grid-cols-1 gap-y-6 gap-x-4 sm:grid-cols-6">
              <div class="sm:col-span-6">
                <%= f.label :title, class: "block text-sm font-medium text-gray-700" %>
                <div class="mt-1">
                  <%= f.text_field :title, class: "block w-full rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm" %>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="pt-5">
          <div class="flex justify-end">
            <%= link_to "Cancel", root_path, class: "rounded-md border border-gray-300 bg-white py-2 px-4 text-sm font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
            <%= f.submit class: "cursor-pointer ml-3 inline-flex justify-center rounded-md border border-transparent bg-indigo-600 py-2 px-4 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/lists/edit.html.erb
<%= render "form", board: @board, list: @list %>

app/views/lists/new.html.erb
<%= render "form", board: @board, list: @list %>